version: '3'

vars:
  VENV_DIR: venv
  REQUIREMENTS_FILE: requirements.txt

tasks:
  # Task to create a virtual environment
  create-venv:
    desc: "Create a virtual environment"
    cmds:
      - python3 -m venv {{.VENV_DIR}}
      - echo "Virtual environment created at {{.VENV_DIR}}."

  # Task to install dependencies from requirements.txt
  install-deps:
    desc: "Install dependencies from requirements.txt"
    cmds:
      - "{{.VENV_DIR}}/bin/pip install -r {{.REQUIREMENTS_FILE}}"
    deps:
      - create-venv
    sources:
      - {{.REQUIREMENTS_FILE}}

  # Task to clean up the virtual environment
  clean:
    desc: "Remove the virtual environment"
    cmds:
      - rm -rf {{.VENV_DIR}}
      - echo "Virtual environment removed."

  # Task to run the application (example)
  run:
    desc: "Run the application"
    cmds:
      - "uvicorn app.main:app --reload" # Replace with your main script path
    deps:
      - install-deps
